name: Enable Dependabot Auto-Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@v3.0.0
