name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    events:
      - open
      - synchronize
jobs:
  ci_push:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@staffbase'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.STAFFBOT_NPM_READ }}
